{% set name = "pysoundfile" %}
{% set pypi_name = "soundfile" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: e8e1017b2cf1dda767aef19d2fd9ee5ebe07e050d430f77a0a7c66ba08b8cdae
  patches:
    # Don't use the wheel-related cmdclass patching, we need to pretend the platform
    # is windows to add an appropriate CFFI function. However, doing so makes the
    # wheel name and metadata indicate it's Windows-only, which is not true.
    - cmdclass.patch

build:
  number: 3
  noarch: python
  script:
    # We are currently building a noarch package, but pysoundfile contains a
    # install-time check for the OS and injects the sf_wchar_open function
    # conditionally. If this variable is not set, opening files on Windows doesn't work
    # Fix coming hopefully with https://github.com/bastibe/python-soundfile/pull/288
    # Original issue on conda-forge: https://github.com/conda-forge/libsndfile-feedstock/issues/14
    - export PYSOUNDFILE_PLATFORM=win32
    - python -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - cffi
  run:
    - python >={{ python_min }}
    - cffi
    - numpy
    - libsndfile >=1.2

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - soundfile
  commands:
    # Verify that soundfile is linking the correct libsndfile object
    - python -c "import soundfile; print(soundfile._libname)"
    # Verify that we can actually access the library
    - python -c "import soundfile as sf, pprint; fmts = sf.available_formats(); pprint.pprint(fmts); assert 'WAV' in fmts"
    - pip show -vvv soundfile
    - pip check -vvv


about:
  home: https://python-soundfile.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'SoundFile is an audio library based on libsndfile, CFFI, and NumPy'
  dev_url: https://github.com/bastibe/python-soundfile

extra:
  recipe-maintainers:
    - scopatz
    - wolfv
    - bmcfee
