{% set name = "pysoundfile" %}
{% set pypi_name = "SoundFile" %}
{% set version = "0.10.2" %}
{% set sha256 = "637f6218c867b8cae80f6989634a0813b416b3e6132480d056e6e5a89a921571" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ pypi_name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1001
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
    - cffi
  run:
    - python
    - cffi
    - numpy
    - libsndfile

test:
  imports:
    - soundfile

about:
  home: http://pysoundfile.readthedocs.io
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'SoundFile is an audio library based on libsndfile, CFFI, and NumPy'
  dev_url: https://github.com/bastibe/SoundFile

extra:
  recipe-maintainers:
    - scopatz
