appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '38'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: eehmz0I9JlLoAvDAAJCgfEYbMoPMbF8sK9V9vXd3v95BMu3D9Z7moV1+LwsEBP0X1A4wQ0NvGL+oNvLpVf++PfwssvYnqIzWYX5hprueLZEEP0lb0I3klSTRoVkcKoJjS0w4dBGWRrNT2TvW9pkJhhYFDw/8Df39ZSX7f4Jzs/tJ05KORtwLwnau+PJx3+PpzKBh8LEgaW/qxh86Y8E67gBn6kwOx66r3DZxaEx3YU4d2WYNNOf6Qr7eM6kazgF/pdjKBysmChG/3xf5Q5CIlOBdNEM3iDCGAYmY/ql+oy6BtCI/N52r8w35jo7jSalofMYv1QZkfiZaKUH/lH4JJWLbPaXwUyKnziHpsl6I8VYbTNEhCKHdj7CFvcTZR7pS119Q7Er6hjytxPMloWzViiE88iLURdmeFOnt20S6hyQ87ZPqbsekZHs99TgHBGQVn76XFbvb2lWQ2niKxsMQTCY2xkcvN6saBOV4X2hXOWWJIyFUTaCCFyEeziA8RTsw+S2TNh/4/g91/V6Tm5R65NtZ/2op4XU1mA8QKv5GPXrvNdsdkAioxel0pOkd8fGue4IeMpwOa+uedqW7PgDvmdFrCX0vHb9nTvE6vrG/FNgiSQiT4n577koWsm8wobRCLOpYtaRawq3W1iRB81/dTGBEQ7okh5HTJjL4yDTWQxE=}
conda_forge_output_validation: true
